# Домашнее задание по Pandas и NumPy.

Общие моменты:

* Обязательно гуглите всю необходимую информацию. Вы можете использовать прочие (которые не упоминались на занятиях) методы и алгоритмы для решения задач, но при условии, что Вы сможете их объяснить. Если Вы нашли какой-то интересный способ решения, то нужно в комментарий добавить ссылку на источник.
* Списывать/плагиатить строго запрещено. Можно использовать готовые решения из интернета только в случае, если Вы укажите ссылку на источник. И поясните, почему лучше так, а не каким-то стандартным (рекомендуемым) способом.
* Желательно (но не обязательно) указывать комментарии в Вашем решении. Это и Вам поможет понять, что Вы делаете. И также это поможет преверяющему в случае вопросов.
* Технологии типа ChatGPT не использовать. 
* В случае каких-то вопросов или спорных ситуаций (например, после получения результатов дз), обращайтесь к ассистенту/преподавателю. И лучше пишите какие-то комментарии к своему коду, чтобы спорных ситуаций было как можно меньше.
* Сдавать ДЗ в SmartLMS!
* Успехов!

## Pandas

Представлены данные о продажах в супермаркете. Файл "supermarket_sales.csv".

Вам требуется открыть файл и проанализировать в нём информацию.

Ниже представлено более детальное описание данных в файле.

* Invoice ID - идентификационный номер счёта-фактуры.
* Branch - филиал/отделение супермаркета, доступно три отделения: A, B и C.
* City - название города, где находится филиал/отделение супермаркета. Доступно три города: Yangon (Янгон), Mandalay (Мандалай) и Naypyitaw (Нейпьидо). Это всё Мьянма.
* Customer type - тип клиента. Member, у кого имеется карта супермаркета, и Normal, у кого карты клиента нет.
* Gender - пол клиента.
* Product line - линейка продуктов/продуктовая линия. Группа товаров по категории.
* Unit price - цена за единицу товара в долларах США.
* Quantity - количество продуктов, купленных клиентом.
* Tax 5% - наголовый сбор в размере 5% при покупке клиентом.
* Total - общая стоимость, включая налог.
* Date - дата покупки.
* Time - время покупки.
* Payment - способ оплаты клиента. Доступно: Ewallet (электронный кошелёк),  cash (наличный расчёт) и Credit card (кредитная карта).
* cogs - стоимость проданных товаров. Тот же Total, но без учёта налог в 5%.
* gross margin percentage - процент валовой прибыли.
* gross income - налог.
* Rating - рейтинг. Рейтинг стратификации клиентов по их общему опыту совершения покупок (по шкале от 1 до 10).





In [162]:
import pandas as pd
import numpy as np

**На слуйчай, если вы работаете в Google Colab**

!!! Комментарий про следующие две ячейки !!!

Чтобы считать файлы в pandas, требуется найти файл "supermarket_sales.csv", который Вы сохранили в Google Drive. Для этого требуется подключить здесь этот Drive. Чтобы уже дальше Вы могли перемещаться по каталогам.

По умолчанию, Ваш файл (как и ipynb файл) может быть тут: "/content/gdrive/My Drive/Colab Notebooks/".
Детальнее эту всю информацию можно уточнить у Вашего преподавателя или ассистента.

Для тех, кто не использует Google Drive, общие рекомендации такие же. Следующие две ячейки можно не запускать, но требуется найти и прописать путь к файлу.

In [163]:
# from google.colab import drive
# drive.mount('/content/gdrive')

In [164]:
# cd /content/gdrive/My Drive/Colab Notebooks/hse/hw_pandas_numpy

In [165]:
# !!! Ваш путь к каталогу и файлу может отличаться. Не забудьте, пожалуйста, про это !!!

Приступаем к домашнему заданию :)

P.S. Ниже Вы увидите основные вопросы и дополнительные к ним. Отвечать нужно на основные вопросы. Где требуется писать код. Остальное (почему так, зачем, из-за чего и другие рассуждения) можете писать в виде комментариев на своё усмотрение.

### Задание 1 (0.25 балла): открыть данные из файла.

Комментарий: требуется просто открыть данные из файла 'supermarket_sales.csv'. Далее мы будем работать с этим через библиотеку pandas.

In [166]:
# Ваш код и комментарии.

supermarket_sales = pd.read_csv('supermarket_sales.csv')
supermarket_sales

Invoice ID Branch       City Customer type  Gender  \
0    750-67-8428      A     Yangon        Member  Female   
1    226-31-3081      C  Naypyitaw        Normal  Female   
2    631-41-3108      A     Yangon        Normal    Male   
3    123-19-1176      A     Yangon        Member    Male   
4    373-73-7910      A     Yangon        Normal    Male   
..           ...    ...        ...           ...     ...   
995  233-67-5758      C  Naypyitaw        Normal    Male   
996  303-96-2227      B   Mandalay        Normal  Female   
997  727-02-1313      A     Yangon        Member    Male   
998  347-56-2442      A     Yangon        Normal    Male   
999  849-09-3807      A     Yangon        Member  Female   

               Product line  Unit price  Quantity   Tax 5%      Total  \
0         Health and beauty       74.69         7  26.1415   548.9715   
1    Electronic accessories       15.28         5   3.8200    80.2200   
2        Home and lifestyle       46.33         7  16.2155   340.5255   
3         Health and beauty       58.22         8  23.2880   489.0480   
4         Sports and travel       86.31         7  30.2085   634.3785   
..                      ...         ...       ...      ...        ...   
995       Health and beauty       40.35         1   2.0175    42.3675   
996      Home and lifestyle       97.38        10  48.6900  1022.4900   
997      Food and beverages       31.84         1   1.5920    33.4320   
998      Home and lifestyle       65.82         1   3.2910    69.1110   
999     Fashion accessories       88.34         7  30.9190   649.2990   

          Date   Time      Payment    cogs  gross margin percentage  \
0     1/5/2019  13:08      Ewallet  522.83                 4.761905   
1     3/8/2019  10:29         Cash   76.40                 4.761905   
2     3/3/2019  13:23  Credit card  324.31                 4.761905   
3    1/27/2019  20:33      Ewallet  465.76                 4.761905   
4     2/8/2019  10:37      Ewallet  604.17                 4.761905   
..         ...    ...          ...     ...                      ...   
995  1/29/2019  13:46      Ewallet   40.35                 4.761905   
996   3/2/2019  17:16      Ewallet  973.80                 4.761905   
997   2/9/2019  13:22         Cash   31.84                 4.761905   
998  2/22/2019  15:33         Cash   65.82                 4.761905   
999  2/18/2019  13:28         Cash  618.38                 4.761905   

     gross income  Rating  
0         26.1415     9.1  
1          3.8200     9.6  
2         16.2155     7.4  
3         23.2880     8.4  
4         30.2085     5.3  
..            ...     ...  
995        2.0175     6.2  
996       48.6900     4.4  
997        1.5920     7.7  
998        3.2910     4.1  
999       30.9190     6.6  

[1000 rows x 17 columns]

Посмотрите внимательно на данные, которые открылись.

Что Вы там видите? Есть что-то интересное?

Обязательно изучите Ваши данные.

В анализе данных это очень и очень важно. Чтобы понимать, с чем и как работать.

### Задание 2 (0.75 балла): детальное изучение данных.

Комментарий: требуется вывести следующие вещи, по которым мы сможем детальнее понять наши данные.

* первые пять строчек нашего DataFrame.
* последние пять строчек.
* размерность (сколько признаков и сколько строчек мы имеем в данных).
* названия нащих признаков.
* типы данных наших признаков. То есть это целые числа, дробные, строчки или что ещё.
* общую информацию про весь DataFrame.
* общую статистическую информацию про наши данных (например, через describe).

In [167]:
# Ваш код и комментарии.
# Выводим первые пять строчек наших данных.

supermarket_sales.head()


Invoice ID Branch       City Customer type  Gender  \
0  750-67-8428      A     Yangon        Member  Female   
1  226-31-3081      C  Naypyitaw        Normal  Female   
2  631-41-3108      A     Yangon        Normal    Male   
3  123-19-1176      A     Yangon        Member    Male   
4  373-73-7910      A     Yangon        Normal    Male   

             Product line  Unit price  Quantity   Tax 5%     Total       Date  \
0       Health and beauty       74.69         7  26.1415  548.9715   1/5/2019   
1  Electronic accessories       15.28         5   3.8200   80.2200   3/8/2019   
2      Home and lifestyle       46.33         7  16.2155  340.5255   3/3/2019   
3       Health and beauty       58.22         8  23.2880  489.0480  1/27/2019   
4       Sports and travel       86.31         7  30.2085  634.3785   2/8/2019   

    Time      Payment    cogs  gross margin percentage  gross income  Rating  
0  13:08      Ewallet  522.83                 4.761905       26.1415     9.1  
1  10:29         Cash   76.40                 4.761905        3.8200     9.6  
2  13:23  Credit card  324.31                 4.761905       16.2155     7.4  
3  20:33      Ewallet  465.76                 4.761905       23.2880     8.4  
4  10:37      Ewallet  604.17                 4.761905       30.2085     5.3

In [168]:
# Ваш код и комментарии.
# Выводим последние пять строчек наших данных.

supermarket_sales.tail()

Invoice ID Branch       City Customer type  Gender         Product line  \
995  233-67-5758      C  Naypyitaw        Normal    Male    Health and beauty   
996  303-96-2227      B   Mandalay        Normal  Female   Home and lifestyle   
997  727-02-1313      A     Yangon        Member    Male   Food and beverages   
998  347-56-2442      A     Yangon        Normal    Male   Home and lifestyle   
999  849-09-3807      A     Yangon        Member  Female  Fashion accessories   

     Unit price  Quantity   Tax 5%      Total       Date   Time  Payment  \
995       40.35         1   2.0175    42.3675  1/29/2019  13:46  Ewallet   
996       97.38        10  48.6900  1022.4900   3/2/2019  17:16  Ewallet   
997       31.84         1   1.5920    33.4320   2/9/2019  13:22     Cash   
998       65.82         1   3.2910    69.1110  2/22/2019  15:33     Cash   
999       88.34         7  30.9190   649.2990  2/18/2019  13:28     Cash   

       cogs  gross margin percentage  gross income  Rating  
995   40.35                 4.761905        2.0175     6.2  
996  973.80                 4.761905       48.6900     4.4  
997   31.84                 4.761905        1.5920     7.7  
998   65.82                 4.761905        3.2910     4.1  
999  618.38                 4.761905       30.9190     6.6

In [169]:
# Ваш код и комментарии.
# Выводим размерность наших данных.

supermarket_sales.shape

(1000, 17)

In [170]:
# Ваш код и комментарии.
# Выводим название колонок/признаков/переменных.

supermarket_sales.columns

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Total', 'Date',
       'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income',
       'Rating'],
      dtype='object')

In [171]:
# Ваш код и комментарии.
# Выводим тип данных по каждому признаку.

supermarket_sales.dtypes

Invoice ID                  object
Branch                      object
City                        object
Customer type               object
Gender                      object
Product line                object
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Total                      float64
Date                        object
Time                        object
Payment                     object
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

In [172]:
supermarket_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Invoice ID               1000 non-null   object 
 1   Branch                   1000 non-null   object 
 2   City                     1000 non-null   object 
 3   Customer type            1000 non-null   object 
 4   Gender                   1000 non-null   object 
 5   Product line             1000 non-null   object 
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64  
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   object 
 11  Time                     1000 non-null   object 
 12  Payment                  1000 non-null   object 
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  

In [173]:
# Ваш код и комментарии.
# Выводим общую информацию про наш DataFrame.

supermarket_sales.describe()

Unit price     Quantity       Tax 5%        Total        cogs  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.00000   
mean     55.672130     5.510000    15.379369   322.966749   307.58738   
std      26.494628     2.923431    11.708825   245.885335   234.17651   
min      10.080000     1.000000     0.508500    10.678500    10.17000   
25%      32.875000     3.000000     5.924875   124.422375   118.49750   
50%      55.230000     5.000000    12.088000   253.848000   241.76000   
75%      77.935000     8.000000    22.445250   471.350250   448.90500   
max      99.960000    10.000000    49.650000  1042.650000   993.00000   

       gross margin percentage  gross income      Rating  
count             1.000000e+03   1000.000000  1000.00000  
mean              4.761905e+00     15.379369     6.97270  
std               6.131498e-14     11.708825     1.71858  
min               4.761905e+00      0.508500     4.00000  
25%               4.761905e+00      5.924875     5.50000  
50%               4.761905e+00     12.088000     7.00000  
75%               4.761905e+00     22.445250     8.50000  
max               4.761905e+00     49.650000    10.00000

### Задание 3 (1 балл): перевести признак Date в единицы измерения времени.

Комментарий: как Вы могли заметить в предпоследней ячейке, признак Date имеет размерность object. Это не совсем то, с чем мы хотим работать, когда говорим про даты и время. Поэтому требуется преобразовать данный признак (Date) в единицы измерения времени. Например, это можно сделать через to_datetime.

In [174]:
# Ваш код и комментарии.

supermarket_sales['Date'] = pd.to_datetime(supermarket_sales['Date'])

### Задание 4 (1 балл): индексация по датам.

Комментарий: хорошо бы сделать индексацию по признаку Date. То есть сделать так, чтобы вместо достаточно абстрактных индексов (номеров строк), у Вас были даты.

Как Вы думаете, для чего это требуется? Насколько это необходимо? Можно ли это не делать? Можно ли сделать индексацию не по Date?

In [175]:
# Ваш код и комментарии.

supermarket_sales['Invoice ID'].value_counts()
supermarket_sales = supermarket_sales.set_index('Invoice ID')

### Задание 5 (1 балл): проверка на пропущенные значения.

Комментарий: проверить, есть ли пропущенные значения (NaN) в нашем DataFrame.

Вариантов проверки может быть несколько. Так что подойдёт любой стандартный способ.

In [176]:
# Ваш код и комментарии.

supermarket_sales.isnull().sum()

Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

### Задание 6 (1 балл): убрать пропущенные значения из данных. На примере признака Unit price.

Комментарий: на основе полученной информации из предыдущего пункта, нужно убрать пустые значения (они есть или нет?) в наших данных. Для признака Unit price. Как это можно сделать?

В какое случае можно удалить строчки с пустыми значениями, а в каком случае не стоит этого делать? Если нет убирать пустые значения, то что с ними делать? На что их заменить? Есть какие-то идеи?

И не забудьте в конце снова проверить на пустые значения. Чтобы точно убедиться, что всё хорошо.

In [177]:
# Ваш код и комментарии.

supermarket_sales['Unit price'] = supermarket_sales['Unit price'].dropna()
supermarket_sales

Branch       City Customer type  Gender            Product line  \
Invoice ID                                                                    
750-67-8428      A     Yangon        Member  Female       Health and beauty   
226-31-3081      C  Naypyitaw        Normal  Female  Electronic accessories   
631-41-3108      A     Yangon        Normal    Male      Home and lifestyle   
123-19-1176      A     Yangon        Member    Male       Health and beauty   
373-73-7910      A     Yangon        Normal    Male       Sports and travel   
...            ...        ...           ...     ...                     ...   
233-67-5758      C  Naypyitaw        Normal    Male       Health and beauty   
303-96-2227      B   Mandalay        Normal  Female      Home and lifestyle   
727-02-1313      A     Yangon        Member    Male      Food and beverages   
347-56-2442      A     Yangon        Normal    Male      Home and lifestyle   
849-09-3807      A     Yangon        Member  Female     Fashion accessories   

             Unit price  Quantity   Tax 5%      Total       Date   Time  \
Invoice ID                                                                
750-67-8428       74.69         7  26.1415   548.9715 2019-01-05  13:08   
226-31-3081       15.28         5   3.8200    80.2200 2019-03-08  10:29   
631-41-3108       46.33         7  16.2155   340.5255 2019-03-03  13:23   
123-19-1176       58.22         8  23.2880   489.0480 2019-01-27  20:33   
373-73-7910       86.31         7  30.2085   634.3785 2019-02-08  10:37   
...                 ...       ...      ...        ...        ...    ...   
233-67-5758       40.35         1   2.0175    42.3675 2019-01-29  13:46   
303-96-2227       97.38        10  48.6900  1022.4900 2019-03-02  17:16   
727-02-1313       31.84         1   1.5920    33.4320 2019-02-09  13:22   
347-56-2442       65.82         1   3.2910    69.1110 2019-02-22  15:33   
849-09-3807       88.34         7  30.9190   649.2990 2019-02-18  13:28   

                 Payment    cogs  gross margin percentage  gross income  \
Invoice ID                                                                
750-67-8428      Ewallet  522.83                 4.761905       26.1415   
226-31-3081         Cash   76.40                 4.761905        3.8200   
631-41-3108  Credit card  324.31                 4.761905       16.2155   
123-19-1176      Ewallet  465.76                 4.761905       23.2880   
373-73-7910      Ewallet  604.17                 4.761905       30.2085   
...                  ...     ...                      ...           ...   
233-67-5758      Ewallet   40.35                 4.761905        2.0175   
303-96-2227      Ewallet  973.80                 4.761905       48.6900   
727-02-1313         Cash   31.84                 4.761905        1.5920   
347-56-2442         Cash   65.82                 4.761905        3.2910   
849-09-3807         Cash  618.38                 4.761905       30.9190   

             Rating  
Invoice ID           
750-67-8428     9.1  
226-31-3081     9.6  
631-41-3108     7.4  
123-19-1176     8.4  
373-73-7910     5.3  
...             ...  
233-67-5758     6.2  
303-96-2227     4.4  
727-02-1313     7.7  
347-56-2442     4.1  
849-09-3807     6.6  

[1000 rows x 16 columns]

In [178]:
# Ваш код и комментарии.
# Не забудьте снова проверить на пустые значения. На всякий случай :)

supermarket_sales.isnull().sum()

Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

Общий комментарий: в предыдущем пункты Вы изучали то, как можно работать с пустыми значениями. Но как быть с выбросами/аномалиями в данных?

Что это такое, Вы знаете? Как их найти/определить? В данном домашнем задании это не требуется, но в общем случае бывает крайне эффективно поработать и с этим тоже.

Как найти возможные выбросы/аномалии? Если они есть, то что с ними делать?

### Задание 7 (1 балл): придумать новый признак (колонку) для наших данных.

Комментарий: Вы видите, что у нас около 20 признаков, по которым описываются данные. Но ведь никто не запрещает придумать (более-менее осознанно) новый признак или признаки. Есть какие-то идеи? И не забудьте, пожалуйста, добавить новый признак в наш DataFrame, когда Вы его придумаете. Только действуйте осторожно, чтобы данные не сломать :) 

Если с придумыванием нового признака возникают некоторые сложности (такое бывает, так как изучение данных требует времени и определённых знаний/умений), то попробуйте добавить "любой" признак. Просто чтобы понимать, что это сделать можно. А будет ли этот признак осмысленным или нет - это уже другой вопрос :)

Например, у Вас есть цена за единицу товара. Или прочий числовой признак. Вы всегда можете взять этот признак (все его строчки подразумевается) и возвести в квадрат. Зачем? Просто чтобы понимать, что так можно сделать.

!!! Но в идеале очень хотелось бы найти/получить какой-то более качественный (если Вы знаете как) признак. !!!

И не забудьте в самом конце добавить Ваш новый признак в DataFrame. Как добавить признак/колонку/переменную в данные pandas? Сколько может быть/будет строчек/значений в новой колонке?

И самое главное. Вы добавили какой-то новый признак в данные. Предположим, что он осмысленный. Почему именно такой? Почему не другой? Как Вы думаете?

In [179]:
# Ваш код и комментарии.
# Создаём новый признак.
supermarket_sales['Total before tax'] = supermarket_sales['Unit price']*supermarket_sales['Quantity']
supermarket_sales

Branch       City Customer type  Gender            Product line  \
Invoice ID                                                                    
750-67-8428      A     Yangon        Member  Female       Health and beauty   
226-31-3081      C  Naypyitaw        Normal  Female  Electronic accessories   
631-41-3108      A     Yangon        Normal    Male      Home and lifestyle   
123-19-1176      A     Yangon        Member    Male       Health and beauty   
373-73-7910      A     Yangon        Normal    Male       Sports and travel   
...            ...        ...           ...     ...                     ...   
233-67-5758      C  Naypyitaw        Normal    Male       Health and beauty   
303-96-2227      B   Mandalay        Normal  Female      Home and lifestyle   
727-02-1313      A     Yangon        Member    Male      Food and beverages   
347-56-2442      A     Yangon        Normal    Male      Home and lifestyle   
849-09-3807      A     Yangon        Member  Female     Fashion accessories   

             Unit price  Quantity   Tax 5%      Total       Date   Time  \
Invoice ID                                                                
750-67-8428       74.69         7  26.1415   548.9715 2019-01-05  13:08   
226-31-3081       15.28         5   3.8200    80.2200 2019-03-08  10:29   
631-41-3108       46.33         7  16.2155   340.5255 2019-03-03  13:23   
123-19-1176       58.22         8  23.2880   489.0480 2019-01-27  20:33   
373-73-7910       86.31         7  30.2085   634.3785 2019-02-08  10:37   
...                 ...       ...      ...        ...        ...    ...   
233-67-5758       40.35         1   2.0175    42.3675 2019-01-29  13:46   
303-96-2227       97.38        10  48.6900  1022.4900 2019-03-02  17:16   
727-02-1313       31.84         1   1.5920    33.4320 2019-02-09  13:22   
347-56-2442       65.82         1   3.2910    69.1110 2019-02-22  15:33   
849-09-3807       88.34         7  30.9190   649.2990 2019-02-18  13:28   

                 Payment    cogs  gross margin percentage  gross income  \
Invoice ID                                                                
750-67-8428      Ewallet  522.83                 4.761905       26.1415   
226-31-3081         Cash   76.40                 4.761905        3.8200   
631-41-3108  Credit card  324.31                 4.761905       16.2155   
123-19-1176      Ewallet  465.76                 4.761905       23.2880   
373-73-7910      Ewallet  604.17                 4.761905       30.2085   
...                  ...     ...                      ...           ...   
233-67-5758      Ewallet   40.35                 4.761905        2.0175   
303-96-2227      Ewallet  973.80                 4.761905       48.6900   
727-02-1313         Cash   31.84                 4.761905        1.5920   
347-56-2442         Cash   65.82                 4.761905        3.2910   
849-09-3807         Cash  618.38                 4.761905       30.9190   

             Rating  Total before tax  
Invoice ID                             
750-67-8428     9.1            522.83  
226-31-3081     9.6             76.40  
631-41-3108     7.4            324.31  
123-19-1176     8.4            465.76  
373-73-7910     5.3            604.17  
...             ...               ...  
233-67-5758     6.2             40.35  
303-96-2227     4.4            973.80  
727-02-1313     7.7             31.84  
347-56-2442     4.1             65.82  
849-09-3807     6.6            618.38  

[1000 rows x 17 columns]

### Задание 8 (1 балл): фильтрация наших данных.

Комментарий: тут всё просто. Есть данные. Давайте придумаем какой-нибудь фильтр для тренировки знаний. Например следующее.

Вывести количество строчек, в которых упоминается город Yangon (Янгон) и оплата через Ewallet (электронный кошелёк). То есть узнать, сколько раз в городе Yangon (Янгон) была оплата по Ewallet (электронный кошелёк).

In [180]:
# Ваш код и комментарии.
supermarket_sales[(supermarket_sales.City == 'Yangon') & (supermarket_sales.Payment == 'Ewallet')]

Branch    City Customer type  Gender            Product line  \
Invoice ID                                                                 
750-67-8428      A  Yangon        Member  Female       Health and beauty   
123-19-1176      A  Yangon        Member    Male       Health and beauty   
373-73-7910      A  Yangon        Normal    Male       Sports and travel   
355-53-5943      A  Yangon        Member  Female  Electronic accessories   
365-64-0515      A  Yangon        Normal  Female  Electronic accessories   
...            ...     ...           ...     ...                     ...   
720-72-2436      A  Yangon        Normal    Male      Food and beverages   
809-69-9497      A  Yangon        Normal  Female      Home and lifestyle   
558-60-5016      A  Yangon        Normal  Female      Home and lifestyle   
139-32-4183      A  Yangon        Member  Female       Sports and travel   
745-74-0715      A  Yangon        Normal    Male  Electronic accessories   

             Unit price  Quantity   Tax 5%     Total       Date   Time  \
Invoice ID                                                               
750-67-8428       74.69         7  26.1415  548.9715 2019-01-05  13:08   
123-19-1176       58.22         8  23.2880  489.0480 2019-01-27  20:33   
373-73-7910       86.31         7  30.2085  634.3785 2019-02-08  10:37   
355-53-5943       68.84         6  20.6520  433.6920 2019-02-25  14:36   
365-64-0515       46.95         5  11.7375  246.4875 2019-02-12  10:25   
...                 ...       ...      ...       ...        ...    ...   
720-72-2436       66.52         4  13.3040  279.3840 2019-03-02  18:14   
809-69-9497       45.68        10  22.8400  479.6400 2019-01-19  19:30   
558-60-5016       33.30         9  14.9850  314.6850 2019-03-04  15:27   
139-32-4183       97.48         9  43.8660  921.1860 2019-03-14  14:19   
745-74-0715       58.03         2   5.8030  121.8630 2019-03-10  20:46   

             Payment    cogs  gross margin percentage  gross income  Rating  \
Invoice ID                                                                    
750-67-8428  Ewallet  522.83                 4.761905       26.1415     9.1   
123-19-1176  Ewallet  465.76                 4.761905       23.2880     8.4   
373-73-7910  Ewallet  604.17                 4.761905       30.2085     5.3   
355-53-5943  Ewallet  413.04                 4.761905       20.6520     5.8   
365-64-0515  Ewallet  234.75                 4.761905       11.7375     7.1   
...              ...     ...                      ...           ...     ...   
720-72-2436  Ewallet  266.08                 4.761905       13.3040     6.9   
809-69-9497  Ewallet  456.80                 4.761905       22.8400     5.7   
558-60-5016  Ewallet  299.70                 4.761905       14.9850     7.2   
139-32-4183  Ewallet  877.32                 4.761905       43.8660     7.4   
745-74-0715  Ewallet  116.06                 4.761905        5.8030     8.8   

             Total before tax  
Invoice ID                     
750-67-8428            522.83  
123-19-1176            465.76  
373-73-7910            604.17  
355-53-5943            413.04  
365-64-0515            234.75  
...                       ...  
720-72-2436            266.08  
809-69-9497            456.80  
558-60-5016            299.70  
139-32-4183            877.32  
745-74-0715            116.06  

[126 rows x 17 columns]

## NumPy

Ниже представлено несколько задач по NumPy.

### Задание 9 (0.25 балла): создать нулевой вектор размерность 10.

Комментарий: требуется создать NumPy вектор, в котором 10 элементов. И каждый этот элемент вектора равен нулю. Нужно это сделать именно автоматически, а не вручную прописывать десять нулей.

Вы же не будете делать всё вручную, если размерность вектора тысяча или больше :) Так что предпочтительнее создать вектор автоматически.

In [181]:
# Ваш код и комментарии.
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Задание 10 (0.25 балла): создать матрицу 3x3 со значениями в диапазоне от 0 до 8.

Комментарий: на выходе должна быть матрица, в которой 9 элементов: от 0 до 8, 8 включаем. Делать данную задачу также автоматически, без прописывания вручную элементов.

К примеру, можно создать NumPy объект из 9 элементов. А дальше его преобразовать в матрицу 3 на 3.

In [182]:
# Ваш код и комментарии.

np.arange(9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Задание 11 (0.5 балла): создать матрица 10x10 со случайными значениями и найти минимальный и максимальный элементы.

Точно такие же комментарии. Создаётся объект 10 на 10. И в нём ищётся то, что нужно. Тоже автоматический поиск.


In [183]:
# Ваш код и комментарии.
f = np.random.randint(100, size = (10,10))
print(f)

[[76 90 59 71 42 39 83 96  5 61]
 [66 46  0 79 80 13 67 60 21 21]
 [45 56 43 85 74 69 70 20 89 91]
 [45  9 46 22 26 35 63 98  3 96]
 [ 7 94 69 95 12 59 25 53 37 85]
 [69 70  8 93 95  9 75 96 88 88]
 [82 39 15 58 47 45 36 28  1 92]
 [77 66 66 42 18 74 50 13 40 50]
 [57 54 99 75 78  9 75 27 52 42]
 [14 74 62 53 94 36 66 23 35 11]]


In [184]:
f.min()

0

In [185]:
f.max()

99

### Задание 12 (1 балл): создать матрицу 10x10, в которой все значения нули, кроме границ. Граничные элементы пускай будут равны единицам.

Комментарий: вспомните про работу со срезами (slice) в Python. Это тут поможет.

Пример: дана матрица 3 на 3, в которой в центре один нулевой элемент, а граница состоит из единиц. Нужно сделать тоже самое, но только в случае матрицы 10 на 10. Всё автоматически.

In [186]:
# Ваш код и комментарии.

z = np.ones(100).reshape(10,10)
z[1:-1,1:-1] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Задание 13 (0.5 балла): поменять местами две строчки матрицы.

Комментарий: тут всё просто, из задания понятно. Сделать всё автоматически. 

Попробуйте вспомнить, как поменять местами значения двух каких-то переменных в Python.

In [187]:
# Ваш код и комментарии.

z = np.ones(100).reshape(10,10)
z[1:-1,1:-1] = 0

z[[0, 1]] = z[[1, 0]]
z

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Задание 14 (0.25 балла): создать массив из 50 элементов (заполнить случайными целыми числами от 0 до 10, 10 не включаем) и для него найти среднее, стандартное отклонение и медиану.

Комментарий: особых комментариев нет. Нужно сделать также всё автоматически.

In [188]:
# Ваш код и комментарии.
g = np.random.randint(10, size = (5,10))
g

array([[1, 1, 6, 8, 9, 0, 1, 7, 9, 4],
       [3, 8, 5, 5, 7, 6, 6, 4, 2, 7],
       [7, 5, 5, 7, 3, 6, 6, 2, 0, 6],
       [7, 6, 9, 9, 8, 2, 0, 9, 6, 9],
       [0, 1, 6, 4, 4, 8, 5, 8, 6, 3]])

In [189]:
print(g.mean())
print(g.std())
print(np.median(g))


5.12
2.761448895054913
6.0


### Задание 15 (0.25 балла): посчитать определитель матрицы 5x5.

Комментарий: допустим, что Вы нашли решение для случая матриц 2x2 или 3x3. Тот же самый алгоритм применить и для матрицы 5x5. То есть не нужно сразу делать для 5x5. А то вдруг сделаете, посчитаете, а окажется, что всё неправильно. Поэтому сначала нужно сделать проверку. И этой проверкой будет отработка на матрицах более низкой размерности. И да, хорошо бы вспомнить, как считать определитель матрицы.

Также всё автоматически.

Матрица может быть любая на Ваш выбор. К примеру, заполненная случайными целыми числами от 0 до 10, 10 не включаем. Для простоты такую можно взять.

In [191]:
# Ваш код и комментарии.

g = np.random.randint(10, size = (5,5))
g

np.linalg.det(g)

-8815.99999999999